### ISSUE TITLE
Add JRCVNC2018U (aka JRC2018_VNC_UNISEX_4iso) template

### ISSUE THREAD

**Issue by jefferis** [natverse/nat.flybrains#45]
@istvantaisz would you be able to add this based on previous examples? You could add this amira surface [JRC2018_VNC_UNISEX_4iso_8bit3-30k.surf.zip](https://github.com/natverse/nat.flybrains/files/4840068/JRC2018_VNC_UNISEX_4iso_8bit3-30k.surf.zip)
 to data-raw and use this

```
$ unu head /GD/projects/WeiLee/vnctemplates/JRC2018_VNC_UNISEX_4iso_8bit.nrrd 
```
to make a .nhdr file as I have done elsewhere
```
NRRD0004
# Created by Nrrd_Writer at Thu Nov 21 20:04:23 GMT 2019
type: uint8
encoding: gzip
endian: big
dimension: 3
sizes: 660 1290 382
space dimension: 3
space directions: (0.4,0,0) (0,0.4,0) (0,0,0.4)
space units: "microns" "microns" "microns"
```
Let me know if you have any trouble! This will help us get high quality support for VNC transforms properly integrated.

**Comment by jefferis** [comment]
PS You'll need to check Bogovic and Saalfeld to get the correct description for number of samples that went into the template ...

**Comment by istvantaisz** [comment]
I made a pull request, could you check it please?
adding JRCVNC2018U template #46

**Comment by istvantaisz** [comment]
hm, looks like I deleted two useful surface files accidentally (I thought they were unused intermediate versions I had locally)
I restore them quickly
