### ISSUE TITLE
Fail to install natverse

### ISSUE THREAD

**Issue by mxdidi** [natverse/nat.flybrains#48]
Hi, I am a newer in R. I ran it in Windows. When I follow the instructions to install natverse, I can't install some packages(elmr,flycircuit,nat.jrcbrains) because of nat.flybrains is not installed.
The error is as follows:
```
Error in as.templatebrain.character("data-raw/JRC2018_MALE_38um_iso_16bit.nrrd",  : 
  x does not specify a valid path!
Error: unable to load R code in package 'nat.flybrains'
Execution halted
ERROR: lazy loading failed for package 'nat.flybrains'
```
As a result, there is no 'natverse' package, I can't use 'library(natverse)'
Could anyone help me? I would appreciate it.

**Comment by jefferis** [comment]
Thanks for the report. Sorry this was a bug introduced by a recent commit. Can you try again now?

**Comment by XunMa1214** [comment]
Yes, I have installed the package successfully. Thank you very much! I really appreciate it.：）

**Comment by jefferis** [comment]
Great!
